import React from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { ShieldCheck, Info, Image as ImageIcon, DownloadCloud } from 'lucide-react';
import { PieChart, Pie, Cell } from 'recharts';
import { usePrice } from '../context/PriceContext';

const AnalyticsDashboard = () => {
  const { analytics, searchId, IMAGE_BASE, theme } = usePrice();

  if (!analytics) return null;

  const handleDownloadPDF = () => {
    try {
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const pageW = doc.internal.pageSize.getWidth();
      const pageH = doc.internal.pageSize.getHeight();

      // Header Banner
      doc.setFillColor(6, 182, 212);
      doc.rect(0, 0, pageW, 32, 'F');
      doc.setFillColor(4, 120, 170);
      doc.rect(0, 26, pageW, 6, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text('PRICEPULSE', 14, 18);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(220, 245, 255);
      doc.text('HYPERLOCAL MATRIX ANALYSIS REPORT', 14, 26);
      doc.text(`Generated  ${new Date().toLocaleString()}`, pageW - 14, 26, { align: 'right' });

      // Product Title
      doc.setTextColor(20, 20, 40);
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text(analytics.product_name || 'Unknown Product', 14, 50);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 110, 130);
      doc.text(`Product / Query ID: ${analytics.product_id || searchId}`, 14, 58);
      doc.text(`Category: ${analytics.category || 'General'}`, 14, 64);

      // KPI Boxes
      const kpiY = 74;
      const kpiH = 22;
      const kpiW = (pageW - 28 - 6) / 3;
      const kpis = [
        { label: 'AVG PRICE', value: `INR ${parseFloat(analytics.average_price).toFixed(2)}`, accent: [6, 182, 212] },
        { label: 'MIN PRICE', value: `INR ${parseFloat(analytics.min_price).toFixed(2)}`, accent: [16, 185, 129] },
        { label: 'MAX PRICE', value: `INR ${parseFloat(analytics.max_price).toFixed(2)}`, accent: [239, 68, 68] },
      ];
      kpis.forEach((kpi, i) => {
        const x = 14 + i * (kpiW + 3);
        doc.setFillColor(...kpi.accent);
        doc.roundedRect(x, kpiY, kpiW, kpiH, 3, 3, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(7);
        doc.setFont('helvetica', 'bold');
        doc.text(kpi.label, x + kpiW / 2, kpiY + 7, { align: 'center' });
        doc.setFontSize(11);
        doc.text(kpi.value, x + kpiW / 2, kpiY + 16, { align: 'center' });
      });

      // Detailed Table
      const volatility = ((analytics.max_price - analytics.min_price) / analytics.average_price * 100).toFixed(1);
      const viText = volatility > 20 ? 'HIGH INSTABILITY' : volatility > 10 ? 'MODERATELY VOLATILE' : 'STABLE MARKET';
      const confScore = Math.min(Math.round((analytics.total_samples / 30) * 100), 100);

      autoTable(doc, {
        startY: kpiY + kpiH + 8,
        head: [['Metric', 'Value']],
        body: [
          ['Product Name', analytics.product_name || 'N/A'],
          ['Product ID', String(analytics.product_id || searchId)],
          ['Community Average Price', `INR ${parseFloat(analytics.average_price).toFixed(2)}`],
          ['Lowest Recorded Price', `INR ${parseFloat(analytics.min_price).toFixed(2)}`],
          ['Highest Recorded Price', `INR ${parseFloat(analytics.max_price).toFixed(2)}`],
          ['Optimal Safe Buy (Min)', `INR ${parseFloat(analytics.fair_range?.low || 0).toFixed(2)}`],
          ['Optimal Safe Buy (Max)', `INR ${parseFloat(analytics.fair_range?.high || 0).toFixed(2)}`],
          ['Volatility Index', `${volatility}%  —  ${viText}`],
          ['Data Confidence Score', `${confScore}%`],
          ['Matrix Nodes Verified', `${analytics.total_samples} data points`],
          ['Category', analytics.category || 'General'],
        ],
        headStyles: { fillColor: [6, 182, 212], textColor: 255, fontStyle: 'bold', fontSize: 9 },
        bodyStyles: { fontSize: 9, textColor: [40, 40, 60] },
        alternateRowStyles: { fillColor: [240, 248, 255] },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 75 } },
        margin: { left: 14, right: 14 },
      });

      // Footer
      const finalY = doc.lastAutoTable.finalY + 12;
      doc.setFillColor(245, 248, 255);
      doc.rect(14, finalY, pageW - 28, 18, 'F');
      doc.setTextColor(100, 110, 140);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.text('Pokemon Team', 18, finalY + 7);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.text('Team Leader: Nirmal Kumar  |  Developer: Tanishq  |  Designer: Taniya Singla  |  Tester: Tanisha Dua', 18, finalY + 13);
      doc.setFontSize(7);
      doc.setTextColor(180, 190, 200);
      doc.text('Auto-generated by PricePulse. Data sourced from community nodes.', pageW / 2, pageH - 8, { align: 'center' });

      doc.save(`PricePulse_Report_${analytics.product_id || searchId}.pdf`);
    } catch (err) {
      console.error('PDF generation failed:', err);
      alert('PDF export failed. Please try again.');
    }
  };

  const confidenceScore = Math.min(Math.round((analytics.total_samples / 30) * 100), 100);
  const isDark = theme === 'dark';
  const PIE_COLORS = isDark ? ['#22d3ee', '#1e293b'] : ['#0891b2', '#e2e8f0'];
  const pieData = [{ name: 'Conf', value: confidenceScore }, { name: 'Rem', value: 100 - confidenceScore }];

  const volatilityIndex = ((analytics.max_price - analytics.min_price) / analytics.average_price * 100);

  let marketClassification = {
    text: '🟢 Stable Market',
    color: 'text-emerald-700 dark:text-emerald-400',
    border: 'border-emerald-200 dark:border-emerald-500/20',
    bg: 'bg-emerald-100 dark:bg-emerald-500/10'
  };
  if (volatilityIndex > 20) marketClassification = {
    text: '🚨 High Instability',
    color: 'text-rose-700 dark:text-rose-400',
    border: 'border-rose-200 dark:border-rose-500/20',
    bg: 'bg-rose-100 dark:bg-rose-500/10'
  };
  else if (volatilityIndex > 10) marketClassification = {
    text: '🟡 Moderately Volatile',
    color: 'text-amber-700 dark:text-amber-400',
    border: 'border-amber-200 dark:border-amber-400/20',
    bg: 'bg-amber-100 dark:bg-amber-400/10'
  };

  return (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
      <div className="md:col-span-2 glass-panel p-8 rounded-[2.5rem] relative overflow-hidden group shadow-[0_0_50px_rgba(6,182,212,0.15)] transition-all duration-500 backdrop-blur-3xl">
        <div className="absolute -right-20 -top-20 w-80 h-80 bg-cyan-400/10 blur-[100px] rounded-full group-hover:bg-cyan-500/15 transition-colors duration-1000"></div>

        <div className="flex justify-between items-start mb-4 relative z-10 flex-wrap gap-2">
          <p className="font-bold text-[10px] uppercase tracking-widest flex items-center gap-2 border border-emerald-200 dark:border-emerald-500/20 bg-emerald-50 dark:bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 px-3 py-1.5 rounded-full backdrop-blur-sm">
            <ShieldCheck size={14} /> Community Consensus Price
          </p>
          <div className="flex items-center gap-2 mt-2 md:mt-0">
            <span className="text-[10px] uppercase font-bold tracking-widest text-slate-500 dark:text-slate-400 bg-white/50 dark:bg-[#161920]/80 border border-slate-200 dark:border-white/10 px-3 py-1.5 rounded-xl border-dashed">ID: {searchId}</span>
            <button
              onClick={handleDownloadPDF}
              className="flex items-center gap-1.5 text-[10px] uppercase font-black tracking-widest px-3 py-1.5 rounded-xl bg-cyan-50 hover:bg-cyan-500 text-cyan-600 hover:text-white dark:bg-cyan-500/10 dark:hover:bg-cyan-500/30 dark:text-cyan-400 transition-all shadow-sm group border border-cyan-200 dark:border-cyan-500/20"
              title="Export Full PDF Report"
            >
              <DownloadCloud size={14} className="group-hover:animate-bounce" /> PDF Report
            </button>
          </div>
        </div>

        <h3 className="text-2xl font-black text-slate-900 dark:text-white mb-3 tracking-tight relative z-10">{analytics.product_name}</h3>

        {/* Price block */}
        <div className="relative z-10 mb-3">
          <h2 className="text-6xl sm:text-7xl lg:text-[6.5rem] font-black text-slate-800 dark:text-white tracking-tighter leading-none flex items-start animate-in fade-in slide-in-from-left-4 duration-1000">
            <span className="text-cyan-500 text-3xl sm:text-4xl lg:text-5xl pr-2 translate-y-2">₹</span>
            <span className="tabular-nums drop-shadow-[0_0_30px_rgba(34,211,238,0.3)]">{parseFloat(analytics.average_price).toFixed(2)}</span>
          </h2>
        </div>

        {/* Optimal Range — always fully visible below price */}
        <div className="relative z-10 mb-2">
          <p className="text-[10px] uppercase font-bold text-slate-400 dark:text-slate-500 tracking-widest mb-1.5 flex items-center gap-1">
            Optimal Range <Info size={11} className="text-slate-300 dark:text-slate-500" />
          </p>
          <div className="flex items-center gap-2 flex-wrap">
            <span className="bg-emerald-50 dark:bg-emerald-500/10 border border-emerald-200 dark:border-emerald-500/20 text-emerald-700 dark:text-emerald-400 text-sm font-black px-3 py-1.5 rounded-xl tabular-nums">
              ₹ {parseFloat(analytics.fair_range.low).toFixed(2)}
            </span>
            <span className="text-slate-400 dark:text-slate-600 font-light text-lg">—</span>
            <span className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-500/20 text-rose-600 dark:text-rose-400 text-sm font-black px-3 py-1.5 rounded-xl tabular-nums">
              ₹ {parseFloat(analytics.fair_range.high).toFixed(2)}
            </span>
          </div>
        </div>

        <div className="mt-8 pt-6 border-t border-slate-100 dark:border-white/10 flex flex-col md:flex-row items-start md:items-center justify-between gap-4 relative z-10">
          <p className="text-xs font-medium text-slate-500 dark:text-slate-400 flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-cyan-500 animate-pulse"></span>
            Verified across <strong className="text-slate-800 dark:text-white mx-1">{analytics.total_samples} nodes</strong>
          </p>
          <div className={`px-3 py-1.5 rounded-full border ${marketClassification.border} ${marketClassification.bg} relative group cursor-help transition-colors`}>
            <p className={`text-[10px] font-black uppercase tracking-widest ${marketClassification.color}`}>
              {marketClassification.text}
            </p>
          </div>
        </div>
      </div>

      <div className="flex flex-col gap-4">
        <div className="glass-panel p-6 rounded-[2rem] flex-1 flex flex-col justify-center relative overflow-hidden items-center group shadow-[0_0_30px_rgba(34,211,238,0.05)] transition-all duration-500">
          <div className="absolute right-0 top-0 w-32 h-32 bg-purple-400/10 blur-[40px] rounded-full"></div>
          <div className="relative hover:scale-105 transition-transform" style={{ width: 112, height: 112 }}>
            <PieChart width={112} height={112}>
              <Pie
                data={pieData}
                cx={56}
                cy={56}
                innerRadius={35}
                outerRadius={48}
                dataKey="value"
                startAngle={90}
                endAngle={-270}
                stroke="none"
              >
                {pieData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={PIE_COLORS[index % PIE_COLORS.length]} />
                ))}
              </Pie>
            </PieChart>
            <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
              <span className="text-xl font-black text-cyan-600 dark:text-cyan-400 leading-none">{confidenceScore}%</span>
            </div>
          </div>
          <p className="text-slate-500 dark:text-slate-500 text-[10px] uppercase font-bold tracking-widest mt-2 relative z-10">Matrix Confidence</p>
        </div>

        {analytics.last_image ? (
          <div className="glass-panel p-6 rounded-[2rem] flex-1 relative overflow-hidden group cursor-pointer min-h-[120px] shadow-sm transition-all duration-500">
            <img src={`${IMAGE_BASE}${analytics.last_image}`} className="absolute inset-0 w-full h-full object-cover opacity-50 dark:opacity-20 group-hover:scale-110 transition-transform duration-1000" alt="Evidence" />
            <div className="absolute inset-0 bg-gradient-to-t from-white via-white/80 to-transparent dark:from-[#0f1115] dark:via-[#0f1115]/60"></div>
            <div className="relative z-10 h-full flex flex-col justify-end">
              <p className="text-slate-800 dark:text-slate-300 text-[9px] uppercase font-black tracking-[0.2em] flex items-center gap-1.5 bg-white/40 dark:bg-black/30 backdrop-blur-md px-3 py-1.5 rounded-full w-fit border border-white/20">
                <ImageIcon size={12} className="text-cyan-500" /> Valid Node Proof
              </p>
            </div>
          </div>
        ) : (
          <div className="bg-slate-50 dark:bg-[#161920] p-6 rounded-[2rem] border border-dashed border-slate-300 dark:border-white/10 flex-1 relative overflow-hidden flex flex-col items-center justify-center min-h-[120px] opacity-80 cursor-not-allowed transition-colors duration-500">
            <ImageIcon size={20} className="text-slate-400 mb-2" />
            <p className="text-slate-500 text-[9px] uppercase font-bold tracking-widest text-center mt-1">No Evidence<br />Synchronized</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default AnalyticsDashboard;
